from __future__ import annotations

from common import OUTPUT_DIR, read_text, write_output


def main() -> None:
    parts = [
        ("# Manuscript Skeleton", ""),
        ("## Introduction", read_text(OUTPUT_DIR / "introduction_draft.md", "Missing introduction draft.")),
        ("## Theoretical Background", read_text(OUTPUT_DIR / "theoretical_background_draft.md", "Missing theoretical background draft.")),
        ("## Hypotheses", read_text(OUTPUT_DIR / "hypotheses_draft.md", "Missing hypotheses draft.")),
        ("## Contributions", read_text(OUTPUT_DIR / "contribution_statement.md", "Missing contribution statement.")),
        ("## Method", "Not generated by this Skill. Use a separate method-design workflow."),
        ("## Results", "Not generated by this Skill."),
        ("## Discussion", "Not generated by this Skill."),
    ]
    content = "\n\n".join(title + ("\n" + body if body else "") for title, body in parts)
    write_output("manuscript_skeleton.md", content)


if __name__ == "__main__":
    main()
